<?php
return [
 "🔥 Mỗi ngày là một cơ hội mới!",
 "💪 Hãy làm việc chăm chỉ hơn hôm qua!",
 "🎯 Làm việc hăng say, thưởng ngay cuối tháng!",
 "🚀 Sáng tạo không giới hạn, đột phá mỗi ngày!",
 "🏆 Chỉ cần cố gắng thêm một chút, bạn sẽ thấy kết quả khác biệt!",
 "😎 Hôm nay bạn lười biếng, ngày mai bạn sẽ tiếc nuối!",
 "🎉 Làm hết sức, chơi hết mình!",
 "💡 Hãy làm điều mà người khác nghĩ rằng bạn không thể!",
 "🚫 Không có gì là không thể nếu bạn quyết tâm!",
 "💰 Thành công không đến từ may mắn, nó đến từ sự chăm chỉ!",
 "🐢 Tốc độ không quan trọng, miễn là bạn không dừng lại!",
 "⏳ Những gì bạn làm hôm nay sẽ quyết định tương lai của bạn!",
 "🔄 Thất bại không phải là dấu chấm hết, đó là bài học để thành công!",
 "📈 Làm nhiều hơn những gì bạn được trả, rồi bạn sẽ được trả nhiều hơn những gì bạn làm!",
 "🔑 Hãy làm tốt nhất có thể, rồi phần còn lại sẽ tự động đến!",
 "🤝 Muốn đi nhanh hãy đi một mình, muốn đi xa hãy đi cùng nhau!",
 "🎯 Thành công chỉ đến khi bạn dám bước ra khỏi vùng an toàn!",
 "🛠 Mỗi ngày là một cơ hội để cải thiện chính mình!",
 "🏅 Sự kiên trì đánh bại tài năng khi tài năng không kiên trì!",
 "🚪 Chỉ cần bạn không từ bỏ, bạn vẫn còn cơ hội!",
 "🌍 Cách tốt nhất để dự đoán tương lai là tạo ra nó!",
 "⚡ Dám mơ lớn, dám hành động mạnh mẽ!",
 "🎬 Hành động ngay bây giờ hoặc hối tiếc mãi mãi!",
 "😊 Hãy đếm niềm vui, đừng đếm khó khăn!",
 "🚧 Cuộc sống không có giới hạn, chỉ có những giới hạn bạn tự đặt ra!",
 "🏆 Thành công không phải là điểm đến, đó là hành trình!",
 "🚀 Bạn không cần phải vĩ đại để bắt đầu, nhưng bạn phải bắt đầu để trở nên vĩ đại!",
 "💥 Nếu bạn muốn có những điều chưa từng có, hãy làm những điều chưa từng làm!",
 "👊 Chỉ cần bạn tin vào chính mình, bạn đã đi được nửa chặng đường!",
 "🔝 Hãy là phiên bản tốt nhất của chính mình mỗi ngày!",
 "🍀 Càng nỗ lực, may mắn càng mỉm cười với bạn!",
 "🎭 Cuộc sống là 10% những gì xảy ra với bạn và 90% cách bạn phản ứng với nó!",
 "💼 Đừng mơ về thành công, hãy làm việc để đạt được nó!",
 "💎 Không có áp lực, không có kim cương!",
 "🛤 Đừng so sánh bản thân với người khác, hãy so sánh với chính bạn của ngày hôm qua!",
 "🔄 Không ai thành công mà không từng thất bại!",
 "🏁 Không quan trọng bạn bắt đầu như thế nào, quan trọng là bạn kết thúc ra sao!",
 "⏳ Hãy kiên trì, bởi vì tất cả những điều tuyệt vời đều cần thời gian!",
 "❌ Bỏ cuộc là cách chắc chắn nhất để thất bại!",
 "🚧 Mỗi thử thách là một cơ hội để trưởng thành!",
 "📊 Thành công là tổng hợp của những nỗ lực nhỏ bé lặp đi lặp lại mỗi ngày!",
 "💭 Một tư duy tích cực có thể thay đổi cả thế giới của bạn!",
 "🧠 Làm việc thông minh hơn, không chỉ chăm chỉ hơn!",
 "🔨 Đừng chờ đợi cơ hội, hãy tạo ra nó!",
 "👀 Bạn có thể làm được, chỉ cần bạn tin vào điều đó!",
 "🎖 Thành công đến với những ai không ngừng nỗ lực!",
 "⏳ Những người thành công không có thời gian để than vãn!",
 "🚀 Đừng giới hạn tiềm năng của bản thân, bạn mạnh mẽ hơn bạn nghĩ!",
 "🤫 Hãy làm việc chăm chỉ trong im lặng và để thành công lên tiếng!"
];